pipeline {
agent {
        docker { image 'node:22.14.0-alpine3.21' }
     }

stages{
  stage('pull docker image'){   
      steps{
        echo 'Pulling hello world docker image..'
        sh 'docker pull hello-world'
      }
    }
  stage('run docker container'){    
    steps{
      echo 'executing docker container..'
      sh 'docker run hello-world'
    }
  }

}
}
