pipeline {
agent {
        docker { image 'node:22.14.0-alpine3.21' }
     }

stages{
  stage('test version'){   
      steps{
        echo 'version test..'
        sh 'node -version'
      }
    }
  stage('run docker container'){    
    steps{
      echo 'executing docker container..'
      sh 'docker run hello-world'
    }
  }

}
}
